name = {internetStatus}
summary = "{internetStatus}"
description = """{Announces internet status and pressing twice opens the internet systray menu. Shortcut: NVDA+Alt+i}"""
author = "{hamidrehzaey}"
url = {https://github.com/hamidrehzaey/internetStatus}
version = {2024.3}
docFileName = {addon_docFileName}
minimumNVDAVersion = {2019.1}
lastTestedNVDAVersion = {2024.3}
updateChannel = {addon_updateChannel}
